In [2]:

import numpy as np
import numpy.ma as ma

In [57]:
a=np.array([0,1,2,3,4,5,6,7])
b=ma.masked_where((a>=5), a)

In [69]:
b

masked_array(data = [0 1 2 3 4 -- -- --],
             mask = [False False False False False  True  True  True],
       fill_value = 999999)

In [62]:
o=ma.getmask(b)

In [66]:
S = ma.masked_array(a, b.mask)


In [72]:
S.filled(fill_value=0)

array([0, 1, 2, 3, 4, 0, 0, 0])

In [71]:
S.filled(fill_value=0)

array([0, 1, 2, 3, 4, 0, 0, 0])

In [73]:
b.mask

array([False, False, False, False, False,  True,  True,  True], dtype=bool)